spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/guessverse
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8089

logging:
  level:
    org.springframework.web: DEBUG

logo:
  dev:
    publishable-key: ${LOGO_DEV_PUBLISHABLE_KEY:}
