CREATE TABLE flag_game_sessions (
    id UUID PRIMARY KEY,
    question_id BIGINT NOT NULL,
    total_score INTEGER NOT NULL DEFAULT 0,
    current_question_reward INTEGER NOT NULL DEFAULT 100,
    hints_used INTEGER NOT NULL DEFAULT 0,
    attempts INTEGER NOT NULL DEFAULT 0,
    current_question INTEGER NOT NULL DEFAULT 1,
    level INTEGER NOT NULL DEFAULT 1,
    correct_answers INTEGER NOT NULL DEFAULT 0,
    total_questions INTEGER NOT NULL DEFAULT 10,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    current_question_letter_hints INTEGER NOT NULL DEFAULT 0,
    info_used BOOLEAN NOT NULL DEFAULT FALSE,
    answer_revealed BOOLEAN NOT NULL DEFAULT FALSE,
    revealed_positions TEXT,
    awaiting_continue BOOLEAN NOT NULL DEFAULT FALSE,
    total_info_hints INTEGER NOT NULL DEFAULT 0,
    total_letters_revealed INTEGER NOT NULL DEFAULT 0,
    total_answers_revealed INTEGER NOT NULL DEFAULT 0,
    current_letter_bank TEXT
);
